#!/bin/sh

BUILDER=http://172.17.42.1:8080

echo
echo
echo "Compiling slug"
git archive --format=tar.gz HEAD -o /tmp/build.tar.gz

echo "Sending to builder"
curl -sf -X POST --form file="@/tmp/build.tar.gz" ${BUILDER}/build

if [ $? != 0 ]; then
  echo "Failed to send to builder, ${BUILDER}"
  exit 128
fi

echo
echo
